<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Laraue.Apps.Identity.Services\Laraue.Apps.Identity.Services.csproj" />
      <ProjectReference Include="..\Laraue.Apps.Identity.Internal.Contracts\Laraue.Apps.Identity.Internal.Contracts.csproj" />
    </ItemGroup>

</Project>
